// anonymous type features:
// 1. encapsulate a set of read-only properties into a single object without explicitly defining a type first
// 2. the type name is generated by the compiler and is not available at the source code level

public class Anonymous {
    static void Main() {
        var apple = new {Item = "apples", Price = 1};
        var onSale = apple with {Price = 2};
        Console.WriteLine(apple);
        Console.WriteLine(onSale);
        Console.WriteLine();
        
        // an array of anonymously typed elements
        var anonArray = new[] {new {FruitType = "apple", Price = 2}, new {FruitType = "banana", Price = 1}}; 
        foreach (var fruit in anonArray) {
            Console.WriteLine(fruit);
        }
    }
}